export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const ISSUES_LIST_REQUEST = 'ISSUES_LIST_REQUEST'
export const ISSUES_LIST_SUCCESS = 'ISSUES_LIST_SUCCESS'
export const ISSUES_LIST_FAIL = 'ISSUES_LIST_FAIL'